### ISSUE TITLE
Export Model to onnx

### ISSUE THREAD

**Issue by kratzl** [VQAssessment/DOVER#15]
Hello I tried to export the model as an onnx model with the following code:

```
import torch

import argparse
import pickle as pkl

import numpy as np
import yaml

from dover.datasets import UnifiedFrameSampler, spatial_temporal_view_decomposition
from dover.models import DOVER

mean, std = (
    torch.FloatTensor([123.675, 116.28, 103.53]),
    torch.FloatTensor([58.395, 57.12, 57.375]),
)


def fuse_results(results: list):
    x = (results[0] - 0.1107) / 0.07355 * 0.6104 + (results[1] + 0.08285) / 0.03774 * 0.3896
    print(x)
    return 1 / (1 + np.exp(-x))


def gaussian_rescale(pr):
    # The results should follow N(0,1)
    pr = (pr - np.mean(pr)) / np.std(pr)
    return pr


def uniform_rescale(pr):
    # The result scores should follow U(0,1)
    return np.arange(len(pr))[np.argsort(pr).argsort()] / len(pr)


def rescale_results(results: list, vname="undefined"):
    dbs = {
        "livevqc": "LIVE_VQC",
        "kv1k": "KoNViD-1k",
        "ltest": "LSVQ_Test",
        "l1080p": "LSVQ_1080P",
        "ytugc": "YouTube_UGC",
    }
    for abbr, full_name in dbs.items():
        with open(f"dover_predictions/val-{abbr}.pkl", "rb") as f:
            pr_labels = pkl.load(f)
        aqe_score_set = pr_labels["resize"]
        tqe_score_set = pr_labels["fragments"]
        tqe_score_set_p = np.concatenate((np.array([results[0]]), tqe_score_set), 0)
        aqe_score_set_p = np.concatenate((np.array([results[1]]), aqe_score_set), 0)
        tqe_nscore = gaussian_rescale(tqe_score_set_p)[0]
        tqe_uscore = uniform_rescale(tqe_score_set_p)[0]
        print(f"Compared with all videos in the {full_name} dataset:")
        print(
            f"-- the technical quality of video [{vname}] is better than {int(tqe_uscore*100)}% of videos, with normalized score {tqe_nscore:.2f}."
        )
        aqe_nscore = gaussian_rescale(aqe_score_set_p)[0]
        aqe_uscore = uniform_rescale(aqe_score_set_p)[0]
        print(
            f"-- the aesthetic quality of video [{vname}] is better than {int(aqe_uscore*100)}% of videos, with normalized score {aqe_nscore:.2f}."
        )


if __name__ == "__main__":

    parser = argparse.ArgumentParser()

    parser.add_argument("-o", "--opt", type=str, default="./dover.yml", help="the option file")

    ## can be your own
    parser.add_argument(
        "-v",
        "--video_path",
        type=str,
        default="./demo/17734.mp4",
        help="the input video path",
    )

    parser.add_argument("-d", "--device", type=str, default="cuda", help="the running device")

    parser.add_argument(
        "-f",
        "--fusion",
        action="store_true",
    )

    args = parser.parse_args()

    with open(args.opt, "r") as f:
        opt = yaml.safe_load(f)

    ### Load DOVER
    evaluator = DOVER(**opt["model"]["args"]).to(args.device)
    evaluator.load_state_dict(torch.load(opt["test_load_path"], map_location=args.device))

    dopt = opt["data"]["val-l1080p"]["args"]

    temporal_samplers = {}
    for stype, sopt in dopt["sample_types"].items():
        if "t_frag" not in sopt:
            # resized temporal sampling for TQE in DOVER
            temporal_samplers[stype] = UnifiedFrameSampler(sopt["clip_len"], sopt["num_clips"],
                                                           sopt["frame_interval"])
        else:
            # temporal sampling for AQE in DOVER
            temporal_samplers[stype] = UnifiedFrameSampler(
                sopt["clip_len"] // sopt["t_frag"],
                sopt["t_frag"],
                sopt["frame_interval"],
                sopt["num_clips"],
            )

    ### View Decomposition
    views, _ = spatial_temporal_view_decomposition(args.video_path, dopt["sample_types"],
                                                   temporal_samplers)

    for k, v in views.items():
        num_clips = dopt["sample_types"][k].get("num_clips", 1)
        views[k] = (((v.permute(1, 2, 3, 0) - mean) / std).permute(3, 0, 1, 2).reshape(
            v.shape[0], num_clips, -1, *v.shape[2:]).transpose(0, 1).to(args.device))

    print(views)

    # Now, export the traced model with the dummy_input
    torch.onnx.export(evaluator, views, "dover.onnx")
```

But I get the following error:

```
Traceback (most recent call last):
  File "export_onnx.py", line 125, in <module>
    torch.onnx.export(evaluator, views, "dover.onnx")
  File "/home/stefan/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/stefan/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/stefan/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/stefan/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/stefan/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/stefan/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/stefan/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/stefan/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/stefan/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/stefan/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/stefan/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/stefan/DOVER/dover/models/evaluator.py", line 149, in forward
    for key in vclips:
  File "/home/stefan/.local/lib/python3.8/site-packages/torch/_tensor.py", line 916, in __iter__
    raise TypeError("iteration over a 0-d tensor")
TypeError: iteration over a 0-d tensor
```

any Idea what I am doing wrong? I just adapted the code of `evaluate_one_video.py` to generate the dummy_input.

**Comment by teowu** [comment]
The `views` here is actually a dict, containing two keys: "technical" and "aesthetic". I guess maybe the error comes here that ONNX does not support to use dicts as inputs.

Maybe you can slightly modify the model and data, and try to pass two independent parameters instead of the dictionary here to the evaluator. The output will not be changed by such refactoring.

**Comment by teowu** [comment]
May be you can refer to this document on how to modify this: https://pytorch.org/docs/stable/onnx.html#id22

**Comment by teowu** [comment]
Hi kratzl,

I have prepared a default onnx conversion script: https://github.com/VQAssessment/DOVER/blob/master/convert_to_onnx.py.

While prepared, you can test a demo video with an onnx runtime:
https://github.com/VQAssessment/DOVER/blob/master/onnx_inference.py.
